### PR TITLE
Fix configuration directory

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by cmoulliard** [comment]
As parent folder could change, we should pass as var/parameter the name of the parent project created under `/var/lib` as it could be `openshit` or `origin` or `minishift`  @geoand

**Comment by geoand** [comment]
I will take a look tomorrow morning :0

**Comment by geoand** [comment]
Actually this task only applies to `oc cluster up`, it's not shared among the different installation methods.
So I don't see any reason for it to be configurable

**Comment by cmoulliard** [comment]
In fact, I did this change originally because the docker daemon was using a different path to access certificates, .... 

See : https://goo.gl/a9XHWD

To be investigated in order to use same paths as define for openshift

**Comment by geoand** [comment]
I haven't delved into it extensively, but I don't think that the symbolic link is actually needed anymore.

**Pull request merged**
